### ISSUE TITLE
Please add license declaration

### ISSUE THREAD

**Issue by rekado** [m-ou-se/tek#1]
Is this the basis for the firmware updater that is provided by trulyergonomic.com [here](http://www.trulyergonomic.com/Truly_Ergonomic_Firmware_Upgrade_Linux_v2_0_0.tar.gz)?  I don't want to have to trust their prebuilt binary and would like to build it from source myself, but the tarball does not contain any sources, nor does it mention any license.

Is this tool Free/Libre Software (aka "Open Source software")?  If so, under what license do you make it available?

Thank you very much for your work!

~~ A (frustrated) TEK user

**Comment by m-ou-se** [comment]
Yes, the tool on trulyergonomic.com should be the unmodified version from this repository.

I'll check the copyright on the different parts before I add a license. I think I own all the copyright, except for `background.png` and `icon.ico`.

Note that there is also a command-line version, which is GPL-licensed: https://github.com/m-ou-se/teck-programmer

**Comment by m-ou-se** [comment]
Added https://github.com/m-ou-se/tek/blob/master/COPYING

**Comment by rekado** [comment]
Thank you for the clarification!
